FROM ubuntu:16.04

RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get -y install wget python-pip

RUN pip install airflow && \
    pip install airflow[rabbitmq] && \
    pip install airflow[celery]

